### ISSUE TITLE
Command help no respon

### ISSUE THREAD

**Issue by AdiRaihan46** [NRAF13/SampBotNraf#1]
Waktu !help nggak ada respon sama sekali tetapi  command yang lain udah bisa semoga bisa diup lagi

**Comment by NRAF13** [comment]
Bisa kok, mungkin salah setting kamunya

**Comment by AdiRaihan46** [comment]
> Bisa kok, mungkin salah setting kamunya

Kok gak bisa lagi ya? Perasaan kemarin bisa

**Comment by NRAF13** [comment]
Bot Host Juga Pengaruh

**Comment by AdiRaihan46** [comment]
Maksudnya? Aku cuma pake glitch.com sama google script buat uptime

Pada tanggal Kam, 24 Jun 2021 14:06, NRAF ***@***.***>
menulis:

**Comment by NRAF13** [comment]
hosting sangat berpengaruh pada performa apapun yang di hosting
