### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Snzy027** [NRAF13/SampBotNraf#2]
Pas !start Embed statistik servernya ga muncul, solusinya gimana min

**Comment by NRAF13** [comment]
Bisa kok, kalo ngk bisa ngk mungkin saya rilis

**Comment by Snzy027** [comment]
Udh aku pm, ada ssannya min

**Comment by Snzy027** [comment]
Tolong bantuannya
![Screenshot_2021-06-14-00-33-46-983_com discord](https://user-images.githubusercontent.com/85831601/121838971-386a0400-cd03-11eb-9291-06bb7bfacb27.jpg)
![Screenshot_2021-06-14-00-38-16-143_com android chrome](https://user-images.githubusercontent.com/85831601/121838987-3f911200-cd03-11eb-85dc-a1b4659d8a9e.jpg)
